// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1, arg2) {
  return window['go']['main']['App']['Chat'](arg1, arg2);
}

export function CheckOllama() {
  return window['go']['main']['App']['CheckOllama']();
}

export function ClearChatHistory(arg1) {
  return window['go']['main']['App']['ClearChatHistory'](arg1);
}

export function ConnectRelay(arg1) {
  return window['go']['main']['App']['ConnectRelay'](arg1);
}

export function ConvertHWPToPDF(arg1, arg2) {
  return window['go']['main']['App']['ConvertHWPToPDF'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DisconnectRelay() {
  return window['go']['main']['App']['DisconnectRelay']();
}

export function GenerateRelayCode() {
  return window['go']['main']['App']['GenerateRelayCode']();
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetKakaoConfig() {
  return window['go']['main']['App']['GetKakaoConfig']();
}

export function GetKakaoStatus() {
  return window['go']['main']['App']['GetKakaoStatus']();
}

export function GetOllamaModels() {
  return window['go']['main']['App']['GetOllamaModels']();
}

export function GetRelayStatus() {
  return window['go']['main']['App']['GetRelayStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetToolList() {
  return window['go']['main']['App']['GetToolList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OcrFromBase64(arg1) {
  return window['go']['main']['App']['OcrFromBase64'](arg1);
}

export function OcrFromFile(arg1) {
  return window['go']['main']['App']['OcrFromFile'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ParseHWP(arg1, arg2) {
  return window['go']['main']['App']['ParseHWP'](arg1, arg2);
}

export function PullOllamaModel(arg1) {
  return window['go']['main']['App']['PullOllamaModel'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetOllamaModel(arg1) {
  return window['go']['main']['App']['SetOllamaModel'](arg1);
}

export function SimpleChat(arg1, arg2) {
  return window['go']['main']['App']['SimpleChat'](arg1, arg2);
}

export function StartKakaoServer() {
  return window['go']['main']['App']['StartKakaoServer']();
}

export function StartOllama() {
  return window['go']['main']['App']['StartOllama']();
}

export function StopKakaoServer() {
  return window['go']['main']['App']['StopKakaoServer']();
}

export function UpdateKakaoConfig(arg1) {
  return window['go']['main']['App']['UpdateKakaoConfig'](arg1);
}
